### PR TITLE
adjust some filemanager translations after review in UI

### PR DESCRIPTION
**Pull request by gnadelwartz**
I dit not find somse stings to ajdust after review in UI, even sosme of them are present for context menu.

grafik

grafik

I guess you used translations provided by original filemanager from usermin/webmin?

### CODE REVIEW

**Comment by qooob** [comment]
Probably those are in `filemin/lang`?

**Comment by gnadelwartz** [comment]
will have a look at filemin/lang, if they are there I provide an update for filemin/lang to webmin.

Now my translation adjustments after reviewing in UI anre in this pull request.
Please merge.

Wish you a nice weekend

**Comment by gnadelwartz** [comment]
thanks for the tip found missing strings (and more) in filemin/lang and create a pull request for JC :-)

**Comment by qooob** [comment]
Thanks! :wink:

**Pull request merged**
