### PR TITLE
add parameter -repo to theme-update

### PR DESCRIPTION
**Pull request by gnadelwartz**
Hi, while using you script for webmin I added an option to change default repo.
Here I provide a backport to youn theme update script, may be you find it useful.

I do translations in githup editor because of better UTF-8 support then in vi on linux.
So I can test changes made on github and only push to your repo when reviewed in my setup.
no more seperate: "adjust translation after reviewing in UI" pull requests :-)

I know I can also use git on command line, but not so used to it.

### CODE REVIEW

**Comment by qooob** [comment]
Kay, hi.

I don't mind multiple commits. I can squash them in one and then merge.

Thank you for your ideas but I don't find useful changing repos. I will keep in mind your effort and maybe use it one day but not just right now.

Regards,
Ilia

**Comment by gnadelwartz** [comment]
it was also not for you more for me because translation in contect of webmin/usermin and authentic can be a challenge ;-) 

You solved it very simple by having everything in /lang only and non_UTF files simply linked to UTF-8 Verssion.

With webmin/usermin you have to deal with config.info, config.info.de, mutilple langs in module.info and a mix of lang / ulang dirs wich may or may not contain UTF-8 transaltions :-(

In this mix it was very helpful for me to try the changes made as easy as possible from my fork ..
may be you can think about going with the HOST and/or REPO varibales without -repo parameter

**Comment by qooob** [comment]
We're working with Jamie to get rid of non-unicode languages. It should happen some time soon.

Thank you.

**Comment by gnadelwartz** [comment]
sounds good! meanwhile I have to deal with it :-), at least I want to finish the german translations for filemin and the modules.info descriptions shown on dashboard

**Comment by qooob** [comment]
Great. Thank you for contributing.

**Comment by qooob** [comment]
Kay, by the way, there is `authentic-theme/help` that you would want to take a look. 😉

**Comment by gnadelwartz** [comment]
I'll have a look :-)

**Comment by gnadelwartz** [comment]
I guess I have to create the file file-mager.de.html ?

**Comment by qooob** [comment]
I suppose. Besides some modules have `.de.UTF-8`.

**Pull request closed without merging**
