### PR TITLE
Catalan language update 20180310

### PR DESCRIPTION
**Pull request by diathesaron**

### CODE REVIEW

**Comment by iliarostovtsev** [comment]
@ **help/** folder what is the right file to use for **.ca**? Is it **editor.ca.UTF-8.html** or **editor.ca.UTF-8.html** - they are quite different?

**Comment by iliarostovtsev** [comment]
I meant to ask **editor.ca.html** or **editor.ca.UTF-8.html**?

**Comment by diathesaron** [comment]
Hi, the right file is editor.ca.UTF-8.html

**Comment by iliarostovtsev** [comment]
Thanks!

**Pull request merged**
