### PR TITLE
Partial update of Dutch translation for v15.00

### PR DESCRIPTION
**Pull request by Rvanlaak**
Rest will follow later

### CODE REVIEW

**Comment by qooob** [comment]
Thanks, Richard! I've added it to the distro. It will be added upon next release.

**Comment by Rvanlaak** [comment]
:+1: why actually isn't the source in the repo? Would be gladd to also make PRs for that.

**Comment by qooob** [comment]
You mean JavaScript?

**Comment by qooob** [comment]
..it's already in source..just beautify it?

**Comment by Rvanlaak** [comment]
Yes, already saw https://github.com/qooob/authentic-theme/issues/22 and did that but how would you like to have the PR then?

**Comment by qooob** [comment]
Alright, please take a look at the root.

**Pull request closed without merging**
