### PR TITLE
Partial translation to czech language.

### PR DESCRIPTION
**Pull request by stuchy3**
Partial translation to czech language. Rest will come in the future.

### CODE REVIEW

**Comment by stuchy3** [comment]
Hi, no it is translation of main part when using in webmin. Rest is left in english... maybe I should remove those untranslated strings so it would not be confusing...

**Comment by qooob** [comment]
By the way, thank you for your translation. You should only translate what's in the file, without adding anything else. If you need left part for Virtualmin - it's not in the theme and it must be added to the Virtualmin.

**Comment by qooob** [comment]
Alright, I will add it to the next release. I saw that there is not everything. Feel free to add more on the next pull request! Thank you!

**Comment by jstourac** [comment]
I'll try to translate rest of it asap and create another merge request.

Thanks too!

**Comment by qooob** [comment]
Ok, please do.

**Pull request closed without merging**
