### PR TITLE
Update authentic-lib.pm

### PR DESCRIPTION
**Pull request by XhmikosR**
Fix erroneous double quote.

### CODE REVIEW

**Comment by qooob** [comment]
Finally code watcher! Thanks, pal!!

I will fix it in 18.31 very soon.

**Comment by XhmikosR** [comment]
@qooob: you should merge and not do what you do the last few releases with the repo. I mean, it's not right to have the same commits with the same messages and also those commits be huge.

**Comment by qooob** [comment]
I will start doing after 18.31 (hopefully ) :) I have cleared the _**.git**_ on 18.30 (removed binaries from it). Now it's only ~30MB agains ~700MB. At the moment they are not synced and besides all, I need to learn more about `git` to make things fluently. I use command line with `git` and I don't want to mess things around.

**Comment by XhmikosR** [comment]
Why did you close this?

Just make sure you commit and push small patches, merge PRs, and when you want a new version use GitHub releases.

You can ask GitHub support to help you out with the git history and stuff, just keep in mind that force pushing will break any forks and requires a good git knowledge from others to fix the issue.

**Comment by qooob** [comment]
That what I already did last night. Man, it was a mess with that git history thing. I will see how it is on 18.31.

I'm switching to release mode (already did actually) and merging pull request instead of closing it and doing it locally.

**Comment by XhmikosR** [comment]
Allright, if you need any help feel free to ping me.

Your git history was extraordinary broken :p

**Comment by qooob** [comment]
What is your XMPP? You can send it to me using an email on my website.

**Comment by XhmikosR** [comment]
I don't use XMPP, but you can find me on IRC at freenode in #mpc-hc-dev or via email / GitHub issues.

**Comment by qooob** [comment]
18.31 is out, please upgrade.

**Comment by XhmikosR** [comment]
Looks good, thanks.

**Pull request closed without merging**
