### PR TITLE
Update de.UTF-8

### PR DESCRIPTION
**Pull request by paskers**
Edited a few umlauts to unicode syntax

### CODE REVIEW

**Comment by qooob** [comment]
Will merge it closer to the new release date! Thanks!!

**Comment by 7starsone** [comment]
why? lol you don't need this on UTF-8... please don't do unuseful stuff... 
;-) Ilia... ...

**Comment by qooob** [comment]
Not sure what you mean?

**Comment by 7starsone** [comment]
I mean that is not required... it's enough to encode the original file to UTF-8 (if it's not already.,.) you don't need to change the text at all ;-)

**Comment by 7starsone** [comment]
just checked the /usr/libexec/webmin/authentic-theme/lang here on CentOS 7
the de.UTF-8 file is already encoded in UTF-8 (BOM-less) so you don't need to edit the text...
you can write "Überweisung" without any issue...

**Comment by paskers** [comment]
I'm sorry for any unnecessary work, but so far German umlauts aren't shown correctly. See attachment.  
Am 17.02.2015 10:45 schrieb 7starsone <notifications@github.com>:just checked the /usr/libexec/webmin/authentic-theme/lang here on CentOS 7
the de.UTF-8 file is already encoded in UTF-8 (BOM-less) so you don't need to edit the text...
you can write "Überweisung" without any issue...

**Comment by 7starsone** [comment]
what browser are you running? to me is impossible... 'cause the browser autolearns what charset you can use... is something on your own

**Comment by 7starsone** [comment]
are you sure to have selected de.UTF-8 as language and not just **de** ?

**Comment by paskers** [comment]
I am so, so sorry! You are right, I selected "de" not "de.UTF-8". 
I just wanted to help ;) 
One last question: Why are the umlauts written in different ways in the language files? Sometimes "ü" and sometimes "&#252;"? 
Am 17.02.2015 10:58 schrieb 7starsone <notifications@github.com>:are you sure to have selected de.UTF-8 as language and not just de ?

**Comment by 7starsone** [comment]
ok, found... you don't have **de.UTF-8** now in the current Virtualmin package
so you got confused, thinking that even UTF-8 needs that... BUT UTF-8 doesn't need that ;-)

you can do this if you want to use UTF-8 entirely without changing anything:
1) go to http://www.motobit.com/util/charset-codepage-conversion.asp
2) download the /webmin/virtual-server/lang/de file
3) copy all the text
4) paste into the field at motobit
5) source iso-8859-1 | destination utf-8
6) copy the result text to a new de.UTF-8 file
7) upload the new file to /webmin/virtual-server/lang/

I don't understand why they don't do this easy thing one time only and then continue to work on that file....

**Comment by 7starsone** [comment]
Ilia,
here you can download the Portuguese pt.UTF-8 for your theme /webmin/authentic-theme/lang
https://mega.co.nz/#!lRoDFSSD!9JS6Fofr2KigyW6TUQqSzyoF5K5oHK6MdmytJTXrPjQ

;-)

**Comment by qooob** [comment]
@7starsone Thank you very much!! Will add it to the next release.

**Pull request merged**
