### PR TITLE
use PATH from miniserv.conf in tehme update

### PR DESCRIPTION
**Pull request by gnadelwartz**
I managed to install webmin on my Synology NAS. by default the git command is not in PATH.
I added my solution to look for git in alternate dirs also to your update script.
see also https://github.com/webmin/webmin/pull/729

### CODE REVIEW

**Comment by qooob** [comment]
Thanks,

Don't you have to export path with existing path?

Example:
```Bash
export PATH=$PATH:`grep path= ${MINICONF}| sed 's/^path=//'`
```

.. because on my installation, for instance, `ppath` key is empty.

**Comment by qooob** [comment]
Kay, hi.

I have made the patch to my update script again, have a look:
https://github.com/qooob/authentic-theme/commit/04def25bc80d375f238e299fa72a7e43138c4b32

I don't think you're exporting path correctly. Webmin config file has `path=` directive that is set in environment configuration but for some strange reason you are using `miniserv.conf` file? Probably  @jcameron is aware once he accepted your commit?

Besides, this code ``grep path= ${MINICONF}| sed 's/^path=//'`` leaks path key as well to the path export command?

I think you need to test it more. I also don't think you need to run your code on Webmin's update script in case `git` command is found.

**Comment by gnadelwartz** [comment]
to answer your first question, Yes it sould be saver to append Webmin path= to PATH variable instead replacing it.

I'm using the `path=` from miniserv.conf because it is used also when updating/installing webmin, but this may be a wrong guess.

Sorry for late response, I had to recover from Dublin :-)

**Comment by qooob** [comment]
Sure. Whenever you can, just try my latest script with your Linux distros to see if ti's working correctly.

**Pull request merged**
