### PR TITLE
Add Traditional Chinese Translation

### PR DESCRIPTION
**Pull request by miyorineko**

### CODE REVIEW

**Comment by qooob** [comment]
Hi, I'm sorry. You commit doesn't seem right?

Could you get the [latest version of English](https://github.com/qooob/authentic-theme/blob/master/lang/en.UTF-8) file and do it from there keeping lines and comments?

**Comment by Sopor-** [comment]
@qooob I noticed that these two have the same number
```
settings_hotkey_custom_8=自定義鏈接 <code>9</code>
settings_hotkey_custom_9=自定義鏈接 <code>9</code>
```

**Comment by qooob** [comment]
Yes, not good.

@miyorineko The language file and translation is done must stay intact in terms of indent and line-spaces. Could you please do it using the latest English-version file?

**Comment by miyorineko** [comment]
Okay, thanks for correcting, I'll redo it later.

**Comment by miyorineko** [comment]
I found the CAT soft had auto "corrected" some keywords for me. I fixed some problems. Sorry for inconvience caused.

**Comment by qooob** [comment]
@miyorineko Thanks! It looks good!

Chinese is so much shorter than English. Wow. Even greater abstraction, I suppose.

I would like to add your name to the list of translators. Should I keep _miyorineko_ or there is better name?

**Comment by qooob** [comment]
Translate this please:

theme_xhred_filemanager_link_to_clipboard=Symbolic link's name `<strong><em>%value</em></strong>` has been copied to clipboard.

**Pull request closed without merging**
