### PR TITLE
Updated Swedish translation for 18.41

### PR DESCRIPTION
**Pull request by Sopor-**

### CODE REVIEW

**Comment by qooob** [comment]
Thanks. I added it.

**Comment by qooob** [comment]
Translate this please:

`theme_xhred_global_go_back_one_page=Go back one page`

**Comment by qooob** [comment]
Actually no! :laughing: 

This one:
`theme_xhred_global_prev_page=Previous Page`

**Comment by Sopor-** [comment]
theme_xhred_global_prev_page=Föregående sida

**Comment by qooob** [comment]
And this one: :smile: 

settings_right_soft_updates_page_options_title=Software updates

**Comment by Sopor-** [comment]
settings_right_soft_updates_page_options_title=Programuppdateringar

**Comment by qooob** [comment]
Translate this please:

theme_xhred_filemanager_link_to_clipboard=Symbolic link's name `<strong><em>%value</em></strong>` has been copied to clipboard.

**Comment by Sopor-** [comment]
Btw, should it really be `link's name` and not `link name`?
`theme_xhred_filemanager_link_to_clipboard=Symbolisk länknamn <strong><em>%value</em></strong> har kopierats till urklippet.`

**Pull request closed without merging**
