### PR TITLE
 use git API for downloading update-from-repo.sh

### PR DESCRIPTION
**Pull request by gnadelwartz**

### CODE REVIEW

**Comment by qooob** [comment]
This is cool! :heart: Thanks a lot.

**Comment by gnadelwartz** [comment]
yeah, seems the advises how to download files from github are almost wrong, I found only one reference to api in one SO comment. everywhere else it was statet use rawgit ...

**Comment by gnadelwartz** [comment]
same issue here https://github.com/roundcube/roundcubemail/issues/6248

Did you already document it on SO?

**Comment by gnadelwartz** [comment]
OK, I'll try it and send you the link ....

**Comment by qooob** [comment]
Thank you.

**Comment by gnadelwartz** [comment]
https://stackoverflow.com/questions/49818899/official-way-to-access-download-files-from-github

**Comment by qooob** [comment]
Good job.

**Pull request merged**
