### PR TITLE
I translated some Japanese.

### PR DESCRIPTION
**Pull request by kosugikun**
ja_JP.UTF8 file updated.

### CODE REVIEW

**Comment by kosugikun** [comment]
The translation is not 100% yet.

**Comment by qooob** [comment]
Thank you. What is your name, how should I call you on the main page for the contributors section?

**Comment by kosugikun** [comment]
My name is Kosugi.

**Comment by kosugikun** [comment]
Please link to https://github.com/kosugikun/

**Comment by qooob** [comment]
Kosugi Kun? Or just Kosugi? :relaxed: Sure, I'll link it.

**Comment by kosugikun** [comment]
Please make it to Kosugikun.

**Comment by kosugikun** [comment]
We will continue to create Japanese translation in a few steps! 
I am glad if you can teach me various things because it is the first time to help development.

**Comment by qooob** [comment]
I would like to help you with advice. Just ask for it.

Arigatou.

**Pull request merged**
